# Generated by Django 3.0.3 on 2020-02-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('profession', models.CharField(choices=[('d', 'Doctor'), ('e', 'Engineer'), ('o', 'Others')], max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.Person', verbose_name='name')),
            ],
        ),
    ]
