# Generated by Django 3.0.3 on 2020-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='symbols/')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
