# Generated by Django 3.0.3 on 2020-05-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetail',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonDetail',
        ),
    ]
