# Generated by Django 3.0.6 on 2020-05-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_testmodel_pic2'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='news/')),
                ('headline', models.CharField(max_length=500)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
