# Generated by Django 3.0.6 on 2020-06-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.ImageField(upload_to='question_signals/')),
                ('option1', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('1', 'option 1'), ('2', 'option 2'), ('3', 'option 3'), ('4', 'option 4')], max_length=100)),
            ],
        ),
    ]
