# Generated by Django 3.0.6 on 2021-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200610_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('today_price', models.CharField(max_length=100)),
                ('yesterday_price', models.CharField(max_length=100)),
            ],
        ),
    ]
