# Generated by Django 3.0.6 on 2021-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_petrolprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolprice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
