# Generated by Django 3.0.6 on 2021-07-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_petrolprice_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolprice',
            name='diesel_today_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petrolprice',
            name='diesel_updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='petrolprice',
            name='diesel_yesterday_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petrolprice',
            name='today_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petrolprice',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='petrolprice',
            name='yesterday_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
