# Generated by Django 3.0.6 on 2021-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210709_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('app_update_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(default='null', max_length=500)),
                ('option3', models.CharField(default='null', max_length=500)),
                ('correct_option', models.CharField(choices=[('1', 'option 1'), ('2', 'option 2'), ('3', 'option 3')], max_length=100)),
            ],
        ),
    ]
